# Generated by Django 5.1.1 on 2024-09-18 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('Pump and Dump', 'Pump and Dump'), ('Wash Trading', 'Wash Trading'), ('Insider Trading', 'Insider Trading'), ('Short and Distort', 'Short and Distort')], max_length=50)),
                ('company_symbol', models.CharField(max_length=10)),
                ('news_url', models.URLField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
